### ISSUE TITLE
Path to file

### ISSUE THREAD

**Issue by orlin** [rthauby/Paige#5]
Please add configuration option to show the relative path before each filename.  I like how the order the files listed corresponds to the order from paige.config (edit correction: the order of these does get mixed up) -- still, adding the paths (perhaps not part of the name link) would make it easier to locate stuff in many ways.  I think the variable indentation, that may result from this, will be helpful too.  Though I imagine others may want a sub-option for 2 columns (so paths & filenames align vertically, if they are separate anyway).

Thanks for the useful tool.

**Comment by rthauby** [comment]
I don't think I'll be adding this anytime soon. Feel free to incorporate yourself if you'd like, I'll be happy to merge it in if you do.
