### ISSUE TITLE
unordered list (style)

### ISSUE THREAD

**Issue by orlin** [rthauby/Paige#7]
Just a trifle, for those who don't care or want to show the count of their source files...  Could we have configuration for `<ul>` instead of `<ol>` (for the still ordered files list)?  Optionally styled - e.g. bullets, squares, etc.

**Comment by rthauby** [comment]
Hmm, I see the point for this, but I really don't want to over-complicate the project. In my eyes, the beauty of this project is in its simplicity. Though adding defaults would solve this, I kind of just want to keep it simple. But again, if you want to add this is send me a pull request later on and I'll include it.
